Add test five
Alicelidel/blablarepository pull request #5
Opened 2023-03-14 03:52 UTC by Inna67rus

Add a function five.py and a test test_five.py

2023-03-14 17:22 UTC, Alicelidel requested changes

2023-03-14 17:22 UTC, Alicelidel commented on lessons/five.py
> +            if i in letters:
тебе надо ключи проверять) ключи дикта 
if i in letters.keys()

2023-03-14 17:22 UTC, Alicelidel commented on lessons/five.py
> +                letters[i] = letters.get(i) + 1 #if such a letter is already in the dict, it increments its count
letters[i]+= 1

2023-03-14 17:22 UTC, Alicelidel commented on lessons/five.py
> +        else:
а зачем тут else?

2023-03-14 17:26 UTC, Inna67rus commented on lessons/five.py
> +        else:
а там после последнего else  я писала return False, типо если букв нету в строке, то False пусть возвращает

2023-03-14 17:26 UTC, Inna67rus commented on lessons/five.py
> +                letters[i] = letters.get(i) + 1 #if such a letter is already in the dict, it increments its count
это сокращенная форма?

2023-03-15 20:50 UTC, valeriyavalyaeva commented on lessons/five.py
> +                letters[i] = letters.get(i) + 1 #if such a letter is already in the dict, it increments its count
@Alicelidel мне тоже интересно

2023-03-15 21:23 UTC, Alicelidel commented on lessons/five.py
> +                letters[i] = letters.get(i) + 1 #if such a letter is already in the dict, it increments its count
ага. есть такое
в жаваскрипте вроде i++ и i--
в питоне есть -= и +=

2023-03-15 21:26 UTC, Alicelidel approved these changes

2023-04-27 17:30 UTC, Inna67rus commented
Resolved conflicts, rebased from master.

2023-04-27 17:30 UTC, merged